In [14]:
import torch

# Create the first tensor with shape (20, 3) with randomly having 1 and two zeros
action = torch.zeros(20, 3)
indices = torch.randint(0, 3, size=(20,)) # randomly choose 0, 1, or 2 for each row
for i, idx in enumerate(indices):
    action[i, idx] = 1

# Create the second tensor with shape (20, 3) with each tensor having a value [1,-1,0]
update_tensor = torch.tensor([[1, -1, 0]] * 20)

# Create the third tensor with shape (20, 1) with random positive values
stock_holdings = torch.rand(20, 1)

# Create the fourth tensor with shape (1, 20) with random positive values
prices = torch.rand(1, 20)

# Perform element-wise multiplication of the first three tensors
tensor4 = action * update_tensor * stock_holdings

# Sum the tensor along the first dimension to get a tensor of shape (1, 20)
tensor4_sum = torch.sum(tensor4)

# Perform element-wise multiplication of the sum tensor and tensor5
result_tensor = tensor4_sum * tensor5
print(action)
print(update_tensor)
print(stock_holdings)
print(prices)
print(torch.sum(tensor4,dim=1,keepdim=False))
print(tensor5)
print(torch.sum(tensor4,dim=1,keepdim=False) * prices)

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])
tensor([[ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0],
        [ 1, -1,  0]])
tensor([[0.3646],
        [0.4249],
        [0.0308],
        [0.6129],
        [0.7628],
        [0.3295],
        [0

In [ ]:
from init_script import init_tensor
import torch

